# generated by chatgpt
import serial

ser = serial.Serial('COM6', 115200, timeout=1)

while True:
    # read a line of text from the serial port
    value = ser.read(1)

    # print the line of text
    printed_val = ord(value) if len(value) > 0 else "empty"
    print(printed_val)
